services:
  - type: web
    name: sgiongs
    env: python
    plan: free
    buildCommand: "pip install -r requirements.txt && python importar_excel.py"
    startCommand: "python wsgi.py"
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.9
